"""anvex core tables

The six tables ported from the legacy `avg_inv` schema: `politicians`, `users`, `stocks`,
`stock_data`, `watchlists` and `watchlist_data`.

Autogenerated from `app/models/` and then hand-formatted; the operations are unchanged, so
`alembic revision --autogenerate` against a database at this revision produces an empty
diff (asserted by `tests/integration/test_models.py`).

Every constraint name comes from the `Base.metadata` naming convention via `op.f()` —
`op.f()` marks a name as already-final so alembic does not apply the convention a second
time. Nothing here names a constraint by hand.

Revision ID: 0002_core_tables
Revises: 0001_bootstrap
Create Date: 2026-08-28

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.settings import get_settings

# revision identifiers, used by Alembic.
revision: str = "0002_core_tables"
down_revision: str | Sequence[str] | None = "0001_bootstrap"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SCHEMA = get_settings().postgres_schema


def upgrade() -> None:
    op.create_table(
        "politicians",
        sa.Column("politician_id", sa.String(length=50), nullable=False),
        sa.Column("state", sa.String(length=5), nullable=True),
        sa.Column("chamber", sa.String(length=50), nullable=True),
        sa.Column("dob", sa.Date(), nullable=True),
        sa.Column("first_name", sa.String(length=80), nullable=False),
        sa.Column("last_name", sa.String(length=80), nullable=False),
        sa.Column("gender", sa.String(length=25), nullable=True),
        sa.Column("party", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("politician_id", name=op.f("pk_politicians")),
        schema=SCHEMA,
    )

    op.create_table(
        "users",
        sa.Column(
            "user_id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
        schema=SCHEMA,
    )

    op.create_table(
        "stocks",
        sa.Column(
            "stock_id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("ticker_symbol", sa.String(length=16), nullable=False),
        sa.Column("company", sa.String(length=150), nullable=False),
        sa.Column("market", sa.String(length=150), nullable=False),
        sa.Column("isin", sa.String(length=12), nullable=True),
        sa.PrimaryKeyConstraint("stock_id", name=op.f("pk_stocks")),
        sa.UniqueConstraint("isin", name=op.f("uq_stocks_isin")),
        sa.UniqueConstraint("ticker_symbol", name=op.f("uq_stocks_ticker_symbol")),
        schema=SCHEMA,
    )
    op.create_index(op.f("ix_stocks_company"), "stocks", ["company"], unique=False, schema=SCHEMA)

    op.create_table(
        "stock_data",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("stock_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("time", sa.Time(), nullable=False),
        sa.Column("open_price", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("high_price", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("low_price", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("close_price", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            [f"{SCHEMA}.stocks.stock_id"],
            name=op.f("fk_stock_data_stock_id_stocks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_data")),
        # ANV-22's ingest upsert conflict target, and the index that serves every
        # "this stock, this date range" read.
        sa.UniqueConstraint(
            "stock_id", "date", "time", name=op.f("uq_stock_data_stock_id_date_time")
        ),
        schema=SCHEMA,
    )
    # Cross-stock date windows cannot use the constraint above — `date` is not its
    # leading column.
    op.create_index(op.f("ix_stock_data_date"), "stock_data", ["date"], unique=False, schema=SCHEMA)

    op.create_table(
        "watchlists",
        sa.Column(
            "watchlist_id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "title",
            sa.String(length=50),
            server_default=sa.text("'My Watchlist'"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            [f"{SCHEMA}.users.user_id"],
            name=op.f("fk_watchlists_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("watchlist_id", name=op.f("pk_watchlists")),
        schema=SCHEMA,
    )
    op.create_index(
        op.f("ix_watchlists_user_id"), "watchlists", ["user_id"], unique=False, schema=SCHEMA
    )

    op.create_table(
        "watchlist_data",
        sa.Column("watchlist_id", sa.Uuid(), nullable=False),
        sa.Column("stock_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            [f"{SCHEMA}.stocks.stock_id"],
            name=op.f("fk_watchlist_data_stock_id_stocks"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["watchlist_id"],
            [f"{SCHEMA}.watchlists.watchlist_id"],
            name=op.f("fk_watchlist_data_watchlist_id_watchlists"),
            ondelete="CASCADE",
        ),
        # A *real* composite primary key. The legacy model faked one with
        # `__mapper_args__ = {"primary_key": [...]}`, which told the ORM what to treat as
        # a key while leaving the table without one.
        sa.PrimaryKeyConstraint("watchlist_id", "stock_id", name=op.f("pk_watchlist_data")),
        schema=SCHEMA,
    )


def downgrade() -> None:
    # Reverse dependency order: children before the tables they reference.
    op.drop_table("watchlist_data", schema=SCHEMA)
    op.drop_index(op.f("ix_watchlists_user_id"), table_name="watchlists", schema=SCHEMA)
    op.drop_table("watchlists", schema=SCHEMA)
    op.drop_index(op.f("ix_stock_data_date"), table_name="stock_data", schema=SCHEMA)
    op.drop_table("stock_data", schema=SCHEMA)
    op.drop_index(op.f("ix_stocks_company"), table_name="stocks", schema=SCHEMA)
    op.drop_table("stocks", schema=SCHEMA)
    op.drop_table("users", schema=SCHEMA)
    op.drop_table("politicians", schema=SCHEMA)
